"""Tabla eventos

Revision ID: d0fcaf5b5a3f
Revises: 487c4cf28936
Create Date: 2019-10-24 23:04:22.423515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fcaf5b5a3f'
down_revision = '487c4cf28936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('lugar', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_fecha'), 'evento', ['fecha'], unique=False)
    op.create_table('asistentes_evento',
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistentes_evento')
    op.drop_index(op.f('ix_evento_fecha'), table_name='evento')
    op.drop_table('evento')
    # ### end Alembic commands ###
